wsgi/openshift/trips/urls.py
from django.conf.urls import patterns, url

from trips import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^public/$', views.public, name='public'),
	url(r'^create/$', views.create, name='create'),
	url(r'^view/(?P<tripid>\d+)/$', views.view, name='view'),
	url(r'^comment/(?P<tripid>\d+)/add/$', views.add_comment, name='add_comment'),
	url(r'^delete/(?P<tripid>\d+)/$', views.delete, name='delete'),
	url(r'^edit/(?P<tripid>\d+)/$', views.edit, name='edit'),
	url(r'^photos/(?P<tripid>\d+)/edit/$', views.edit_photos, name='edit_photos'),
	url(r'^photos/(?P<tripid>\d+)/add/$', views.add_photos, name='add_photos'),
	url(r'^share/(?P<tripid>\d+)/$', views.share, name='share'),
	url(r'^share/(?P<tripid>\d+)/remove/(?P<userid>\d+)/$', views.remove_user, name='remove_user'),
	url(r'^share/(?P<tripid>\d+)/add/(?P<userid>\d+)/$', views.add_user, name='add_user'),	
	url(r'^share/(?P<tripid>\d+)/removegroup/(?P<groupid>\d+)/$', views.remove_group, name='remove_group'),
	url(r'^share/(?P<tripid>\d+)/addgroup/(?P<groupid>\d+)/$', views.add_group, name='add_group'),	
)

wsgi/openshift/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
admin.autodiscover()

# include urls patterns and paths from individual apps
urlpatterns = patterns('',
	url(r'^$', 'views.home', name='home'),
	url(r'^dashboard/$', 'views.dashboard', name='dashboard'),
	url(r'^users/', include('users.urls', namespace='users')),
	url(r'^groups/', include('groups.urls', namespace='groups')),
	url(r'^trips/', include('trips.urls', namespace='trips')),
	url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
	#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT, show_indexes=True)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, show_indexes=True)

wsgi/openshift/users/urls.py
from django.conf.urls import patterns, url
from django.core.urlresolvers import reverse

from users import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^profile/(?P<username>\w+)/$', views.profile, name='profile'),
	url(r'^registration/$', views.registration, name='registration'),
	url(r'^login/$', views.user_login, name='login'),
	url(r'^logout/$', views.user_logout, name='logout'),
	url(r'^edit/$', views.edit, name='edit'),
	url(r'^password_change/$', views.password_change, name='password_change'),
	url(r'^search/$', views.search, name='search'),
)

wsgi/openshift/trips/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
import os, Image
from uuid import uuid4
from datetime import datetime
from groups.models import CustomGroup

#helper function generating random names for avatars
def path_and_rename(path):
	def wrapper(instance, filename):
		ext = filename.split('.')[-1]
		# set filename as random string
		filename = '{0}.{1}'.format(uuid4().hex, ext.lower())
		# return the whole path to the file
		# check type of instance and determine correct save path
		if (type(instance) is Trip):
			return os.path.join(path, str(instance.owner.id), filename)
		else: # type(instance) is Photo
			return os.path.join(path, str(instance.trip.owner.id), filename)
	return wrapper

# Trip model with all fields related with real trips
class Trip(models.Model):
	#basic trip properties
	title = models.CharField(_('title'), max_length=80)
	owner = models.ForeignKey(User)
	trip_begin = models.DateTimeField(_('trip begin'))
	trip_end = models.DateTimeField(_('trip end'))
	description = models.TextField(_('description'), blank=True)
	gpx_log = models.FileField(upload_to=path_and_rename('gpx'), blank=True)
	
	created = models.DateTimeField(auto_now_add=True)
	modified = models.DateTimeField(auto_now=True)

	#sharing options
	public = models.BooleanField(_('public trip'), default=False, help_text=_('If checked, everyone can view this trip regardless of sharing with users and/or groups'))
	share_users = models.ManyToManyField(User, verbose_name=_('share with users'),
        blank=True, help_text=_('The users sharing this trip.'),
        related_name="shared_trips", related_query_name="trips")
	share_groups = models.ManyToManyField(CustomGroup, verbose_name=_('share with groups'),
        blank=True, help_text=_('The groupss sharing this trip.'),
        related_name="shared_trips", related_query_name="trips")

	# helper function for validation that trip begins before it ends
	def validate_trip_begin_end(self):        
		if self.trip_begin > self.trip_end:
			raise ValidationError(_('Trip must ends after it begins'))

	# helper function for validation uniqe trip title per user
	def validate_unique_title_owner(self):        
		qs = Trip.objects.filter(title=self.title)
		if self.id:
			qs = qs.exclude(id=self.id)
		if qs.filter(owner=self.owner).exists():
			raise ValidationError(_('Trip title must be unique per user'))

	# Override save() due to custom validation
	def save(self):
		self.validate_trip_begin_end()
		self.validate_unique_title_owner()
		super(Trip, self).save()

	# Override the __unicode__() method to return out something meaningful
	def __unicode__(self):
		return self.title + '__' + self.owner.username

# comment model with reference to author, trip and comment message
class Comment(models.Model):
	trip = models.ForeignKey(Trip)
	author = models.ForeignKey(User)
	message = models.TextField(_('message'), max_length=80, blank=False)
	created = models.DateTimeField(auto_now_add=True)

	# Override the __unicode__() method to return out something meaningful
	def __unicode__(self):
		return self.trip.title + '__' + self.author.username + "__" + self.message[0:40]

# comment model with reference to trip, photo image and thumbnail and text photo title
class Photo(models.Model):
	trip = models.ForeignKey(Trip)
	title = models.CharField(_('title'), max_length=80, blank=True)
	image = models.ImageField(upload_to=path_and_rename('photos'), blank=False)
	thumb = models.ImageField(upload_to=path_and_rename('photos_thumb'), blank=True)

	# Override the __unicode__() method to return out something meaningful
	def __unicode__(self):
		return self.trip.title + '__' + os.path.basename(self.image.url)

	# Override save() due to create thumbnail of the photo
	def save(self):
		self.thumb.save(self.image.path, self.image, save=False)
		super(Photo, self).save()
		create_thumbnail(self.thumb)

THUMB_SIZE = (160, 160)
# create thumbnail from full-size photo image
def create_thumbnail(thumb):
	img = Image.open(thumb.path)
	w, h = img.size
	if w < h:
		img = img.crop((0, 0, w, w))
	else:
		img = img.crop(((w-h)/2, 0, w-(w-h)/2, h)) 
	img = img.resize(THUMB_SIZE, Image.ANTIALIAS)
	img.save(thumb.path)

wsgi/openshift/trips/forms.py
from django import forms
from trips.models import Trip, Comment

# Form with user-accessible fields from trip model
class TripForm(forms.ModelForm):
	class Meta:
		model = Trip
		fields = ('title', 'trip_begin', 'trip_end', 'description', 'gpx_log', 'public')

	# add special class to datetime fields due to datetimepicker jquery plugin
	def __init__(self, *args, **kwargs):
		super(TripForm, self).__init__(*args, **kwargs)
		self.fields['trip_begin'].widget.attrs['class'] = 'datetimepicker'
 		self.fields['trip_end'].widget.attrs['class'] = 'datetimepicker'

# Form with user-accessible fields from comment model
class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ('message',)

wsgi/openshift/trips/views.py
from django.core.urlresolvers import reverse
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from django.shortcuts import get_object_or_404, render, render_to_response
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse
from django.template.context import RequestContext
from django.views.decorators.csrf import csrf_protect
from groups.models import CustomGroup
from trips.models import Trip, Comment, Photo
from trips.forms import TripForm, CommentForm


# view for display list of user's trips
@login_required
def index(request):
	context = RequestContext(request)
	user = request.user
	trips = user.trip_set.all().order_by('-id')
	return render_to_response('trips/index.html', {'trips': trips}, context)


# view for display list of all users public trips
def public(request):
	context = RequestContext(request)
	trips = Trip.objects.filter(public=True).order_by('-id')
	return render_to_response('trips/public.html', {'trips': trips}, context)


# view for display handle creation of new trip
@csrf_protect
@login_required
def create(request):
	context = RequestContext(request)
	if request.method == 'POST':
		trip_form = TripForm(data=request.POST)
		if trip_form.is_valid():
			trip = trip_form.save(commit=False)
			user = request.user
			trip.owner = user
			if 'gpx_log' in request.FILES:
				trip.gpx_log = request.FILES['gpx_log']
			try:
				trip.save()
				messages.success(request, _('Successfully created trip ') + trip.title)
				return HttpResponseRedirect(reverse('trips:index'))
			except ValidationError, e:
				messages.error(request, e.message)
		else:
			messages.error(request, trip_form.errors)
	else:
		trip_form = TripForm()

	return render_to_response('trips/create.html', {'form': trip_form}, context)


# view for display information about concrete trip
def view(request, tripid):
	context = RequestContext(request)
	user = request.user
	try:
		trip = Trip.objects.get(pk=tripid)
		if __shared_trip(trip, user):
			photos = trip.photo_set.all()
			comments = trip.comment_set.all().order_by('-id')
			comment_form = None
			if (user.is_authenticated()):
				comment_form = CommentForm()
			return render_to_response('trips/view.html', {'trip': trip, 'photos': photos, 'comments': comments, 'comment_form': comment_form}, context)
		else:
			messages.error(request, _('You are not allowed to view this trip.'))
	except Trip.DoesNotExist:
		messages.error(request, _('You can not view non-existing trip.'))
	
	return HttpResponseRedirect(reverse('home'))

# view for handle adding comments to the trip
@csrf_protect
@login_required
def add_comment(request, tripid):
	context = RequestContext(request)
	user = request.user
	try:
		trip = Trip.objects.get(pk=tripid)
		if __shared_trip(trip, user):
			if request.method == 'POST':
				comment_form = CommentForm(data=request.POST)
				if comment_form.is_valid():
					comment = comment_form.save(commit=False)
					comment.author = user
					comment.trip = trip
					try:
						comment.save()
						messages.success(request, _('Successfully added comment.'))
					except ValidationError, e:
						messages.error(request, e.message)
				else:
					messages.error(request, comment_form.errors)

			return HttpResponseRedirect(reverse('trips:view', args=(tripid,)))
		else:
			messages.error(request, _('You are not allowed to comment this trip.'))

	except Trip.DoesNotExist:
		messages.error(request, _('You can not comment non-existing trip.'))
	
	return HttpResponseRedirect(reverse('home'))


# view for handle adding photos to the trip
@csrf_protect
@login_required
def add_photos(request, tripid):
	context = RequestContext(request)
	user = request.user
	try:
		trip = Trip.objects.get(pk=tripid)
		if __shared_trip(trip, user):
			if (request.method == 'POST') and ('file' in request.FILES):
				photo = Photo(image=request.FILES['file'])
				photo.trip = trip
				try:
					photo.save()
					#messages.success(request, _('Successfully upload photo.'))
					return render_to_response('trips/photos_add.html', {'photo': photo}, context)					
				except ValidationError, e:
					messages.error(request, e.message)

			return HttpResponseRedirect(reverse('trips:edit_photos', args=(tripid,)))

		else:
			messages.error(request, _('You are not allowed to add photo to this trip.'))
			return HttpResponseRedirect(reverse('trips:view', args=(tripid,)))


	except Trip.DoesNotExist:
		messages.error(request, _('You can not add photo to non-existing trip.'))
	
	return HttpResponseRedirect(reverse('home'))


# view for display and handle editation photos from the trip
@csrf_protect
@login_required
def edit_photos(request, tripid):
	context = RequestContext(request)
	user = request.user
	try:
		trip = Trip.objects.get(pk=tripid)
		photos = trip.photo_set.all()
		if __shared_trip(trip, user):
			if request.method == 'POST':
				try:
					for photo in photos:
						id = str(photo.id)
						if request.POST.has_key(id):
							edited_photo = request.POST.get(id)
							if photo.title != edited_photo:
								photo.title = edited_photo
								photo.save()
						else:
							photo.delete()

					photos = trip.photo_set.all()
					messages.success(request, _('Successfully edited photos.'))
				except ValidationError, e:
					messages.error(request, e.message)
				except ValueError, e:
					messages.error(request, e.message)

			return render_to_response('trips/photos_edit.html', {'trip': trip, 'photos': photos}, context)

		else:
			messages.error(request, _('You are not allowed to edit photos of this trip.'))
			return HttpResponseRedirect(reverse('trips:view', args=(tripid,)))

	except Trip.DoesNotExist:
		messages.error(request, _('You can not edit photos of non-existing trip.'))
	
	return HttpResponseRedirect(reverse('home'))


# view for handle delete the trip
@login_required
def delete(request, tripid):
	context = RequestContext(request)
	user = request.user
	try:
		trip = Trip.objects.get(pk=tripid)
		if trip.owner == user:
			trip.delete()
			messages.info(request, _('Succesfully deleted trip ') + trip.title)
		else:
			messages.error(request, _('You have not permission to delete foreign trip.'))
	except Trip.DoesNotExist:
		messages.error(request, _('You can not delete non-existing trip.'))
	
	return HttpResponseRedirect(reverse('trips:index'))


# view for display and handle editation of the trip
@csrf_protect
@login_required
def edit(request, tripid):
	context = RequestContext(request)
	user = request.user
	try:
		trip = Trip.objects.get(pk=tripid)
		if trip.owner != user:
			messages.error(request, _('You have not permission to edit foreign trip.'))
			return HttpResponseRedirect(reverse('trips:index'))
		if request.method == 'POST':
			trip_form = TripForm(data=request.POST, instance=trip)
			if trip_form.is_valid():
				trip = trip_form.save(commit=False)
				if 'gpx_log' in request.FILES:
					trip.gpx_log = request.FILES['gpx_log']
				try:
					trip.save()
					messages.success(request, _('Successfully edited trip ') + trip.title)
					#trip_form = TripForm(instance=trip) #for refreshing gpx log
					return HttpResponseRedirect(reverse('trips:view', args=(tripid,)))
	
				except ValidationError, e:
					messages.error(request, e.message)
					trip = Trip.objects.get(pk=tripid)
			else:
				messages.error(request, trip_form.errors)
		else:
			trip_form = TripForm(instance=trip)
	except Trip.DoesNotExist:
		messages.error(request, _('You are not allowed to edit non-existing group.'))
		return HttpResponseRedirect(reverse('trips:index'))
	
	return render_to_response('trips/edit.html', {'trip': trip, 'form': trip_form}, context)

# view for display share page of the trip
@login_required
def share(request, tripid):
	context = RequestContext(request)
	user = request.user
	try:
		trip = Trip.objects.get(pk=tripid)
		if trip.owner != user:
			messages.error(request, _('You have not permission to share foreign trip.'))
			return HttpResponseRedirect(reverse('trips:index'))
	except Trip.DoesNotExist:
		messages.error(request, _('You are not allowed to share non-existing trip.'))
		return HttpResponseRedirect(reverse('trips:index'))
	
	return render_to_response('trips/share.html', {'trip': trip, 'users': trip.share_users.all(), 'groups': trip.share_groups.all(), 'user_groups': user.customgroup_set.all()}, context)

# view for handle removing user from sharing existing tripp
@login_required
def remove_user(request, tripid, userid):
	context = RequestContext(request)
	user = request.user
	try:
		trip = Trip.objects.get(pk=tripid)
		if trip.owner == user:
			deleted_user = trip.share_users.filter(id=userid).first()
			if deleted_user != None:
				trip.share_users.remove(deleted_user)
				messages.info(request, _('Successfully unshared with user ') + deleted_user.username)
			else:
				messages.error(request, _('You can not unshare trip with requested user.'))
		else:
			messages.error(request, _('You have not permission to share foreign trip.'))
	except Trip.DoesNotExist:
		messages.error(request, _('You can not share non-existing trip.'))
	
	return HttpResponseRedirect(reverse('trips:share', args=(tripid,)))

# view for handle adding user for sharing existing tripp
@login_required
def add_user(request, tripid, userid):
	context = RequestContext(request)
	user = request.user
	try:
		trip = Trip.objects.get(pk=tripid)
		if trip.owner == user:
			added_user = trip.share_users.filter(id=userid).first()
			if added_user != None:
				messages.info(request, _('This trip is already shared with user ') + added_user.username)
			else:
				try:
					added_user = User.objects.get(pk=userid)
					trip.share_users.add(added_user)
					messages.success(request, _('Successfully shared with user ') + added_user.username)
				except User.DoesNotExist:
					messages.error(request, _('You can not shared with non-existing user.'))

wsgi/openshift/trips/templates/trips/edit.html
{% extends "base.html" %}

{% load i18n %}

{% block content %}
<h2>{% trans "Edit trip " %}<a href="{% url 'trips:view' trip.id %}" data-ajax="false" >{{ trip.title }}</a></h2>

<form id="trip_edit" method="post" action="{% url 'trips:edit' trip.id %}" enctype="multipart/form-data" data-ajax="false" >
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" data-icon="edit" value="{% trans 'Edit trip' %}" />
</form>

<div data-role="controlgroup" data-type="horizontal">
	<a href="{% url 'trips:edit_photos' trip.id %}" class="ui-btn ui-corner-all ui-shadow ui-icon-camera ui-btn-icon-left" data-ajax="false" >{% trans 'Photos' %}</a>
	<a href="{% url 'trips:share' trip.id %}" class="ui-btn ui-corner-all ui-shadow ui-icon-user ui-btn-icon-left" data-ajax="false" >{% trans 'Share trip' %}</a>
	<a href="#delete" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn ui-corner-all ui-shadow ui-icon-delete ui-btn-icon-left">{% trans 'Delete trip' %}</a>
</div>

<div data-role="popup" id="delete" class="ui-content" >
	<h3>{% trans 'Delete trip' %} {{ trip.name }}?</h3>
	<a href="" data-role="button" data-rel="back" data-icon="back" data-inline="true" data-mini="true">{% trans 'Cancel' %}</a>
	<a href="{% url 'trips:delete' trip.id %}" data-role="button" data-icon="delete" data-inline="true" data-mini="true" data-ajax="false" >Delete</a>
</div>
{% endblock %}

wsgi/openshift/trips/templates/trips/index.html
{% extends "base.html" %}

{% load i18n %}

{% block content %}
<h2>{% trans "My trips" %} </h2>

<p><a href="{% url 'trips:create' %}" data-ajax="false" >{% trans 'Create new trip' %}</a></p>

{% if trips %}
<ul data-role="listview" data-filter="true" data-filter-placeholder="{% trans 'Search trips...' %}" data-inset="true" data-split-icon="edit">
	{% for trip in trips %}
	<li><a href="{% url 'trips:view' trip.id %}" data-ajax="false" ><h3>{{ trip.title }}</h3><p>{{ trip.description|slice:"0:80" }}</p></a><a href="{% url 'trips:edit' trip.id %}" data-ajax="false" >{% trans 'Edit' %}</a></li>
	{% endfor %}
</ul>

{% else %}
<p>{% trans "You have not created any trips yet." %}</p>
{% endif %}

{% endblock %}

wsgi/openshift/trips/templates/trips/share.html
{% extends "base.html" %}

{% load staticfiles %}
{% load i18n %}

{% block content %}
<h2>{% trans "Share trip" %} <a href="{% url 'trips:view' trip.id %}" data-ajax="false" >{{ trip.title }}</a></h2>

<script src="{% static 'js/user_add_autocomplete.js' %}"></script>

<ul id="user_add" data-role="listview" data-inset="true" data-filter="true" data-filter-placeholder="{% trans 'Search user for sharing this trip...' %}" data-split-icon="plus" >
</ul>

<ul data-role="listview" data-inset="true" data-split-icon="delete">
	<li data-role="list-divider">Trip shared with users:</li>
	{% for user in users %}
	<li><a href="{% url 'users:profile' user.username %}" ><img src="{{ user.userprofile.avatar.url }}" alt="{{ user.username }}" /><h3>{{ user.username }}</h3><p>{{ user.get_full_name }}</p></a><a href="#remove{{ user.id }}" data-rel="popup" data-position-to="window" data-transition="pop" >{% trans 'Remove' %}</a></li>
	{% endfor %}
</ul>

<ul id="group_add" data-role="listview" data-inset="true" data-filter="true"data-filter-reveal="true" data-filter-placeholder="{% trans 'Search group for sharing this trip...' %}" data-split-icon="plus" >
	{% for group in user_groups %}
	<li><a href="{% url 'groups:edit' group.id %}" data-ajax="false" ><h3>{{ group.name }}</h3></a><a href="{% url 'trips:add_group' trip.id group.id %}" data-ajax="false" >{% trans 'Add' %}</a></li>
	{% endfor %}

</ul>

<ul data-role="listview" data-inset="true" data-split-icon="delete">
	<li data-role="list-divider">Trip shared with groups:</li>
	{% for group in groups %}
	<li><a href="{% url 'groups:edit' group.id %}" data-ajax="false" ><h3>{{ group.name }}</h3></a><a href="#removegroup{{ group.id }}" data-rel="popup" data-position-to="window" data-transition="pop" >{% trans 'Remove' %}</a></li>
	{% endfor %}
</ul>

{% for user in users %}
<div data-role="popup" id="remove{{ user.id }}" class="ui-content" >
	<h3>{% trans 'Remove user' %} {{ user.name }}?</h3>
	<a href="" data-role="button" data-rel="back" data-icon="back" data-inline="true" data-mini="true">{% trans 'Cancel' %}</a>
	<a href="{% url 'trips:remove_user' trip.id user.id %}" data-role="button" data-icon="delete" data-inline="true" data-mini="true" data-ajax="false" >Remove</a>
</div>
{% endfor %}

{% for group in groups %}
<div data-role="popup" id="removegroup{{ group.id }}" class="ui-content" >
	<h3>{% trans 'Remove group' %} {{ group.name }}?</h3>
	<a href="" data-role="button" data-rel="back" data-icon="back" data-inline="true" data-mini="true">{% trans 'Cancel' %}</a>
	<a href="{% url 'trips:remove_group' trip.id group.id %}" data-role="button" data-icon="delete" data-inline="true" data-mini="true" data-ajax="false" >Remove</a>
</div>
{% endfor %}

{% endblock %}

wsgi/openshift/trips/templates/trips/view.html
{% extends "base.html" %}

{% load staticfiles %}
{% load i18n %}

{% block extrahead %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/leaflet.min.css' %}" />
	
	<script src="{% static 'js/leaflet.js' %}"></script>

	{% if trip.gpx_log %}
		<link rel="stylesheet" type="text/css" href="{% static 'css/Leaflet.Elevation-0.0.2.css' %}" />

		<!--<script src="{% static 'js/leaflet-gpx.js' %}"></script>-->
		<script src="{% static 'js/leaflet-gpx.min.js' %}"></script>
		<script src="{% static 'js/d3.v3.min.js' %}"></script>
		<script src="{% static 'js/Leaflet.Elevation-0.0.2.min.js' %}"></script>
		<script src="{% static 'js/map.js' %}"></script>
	{% endif %}
	
	{% if photos %}
			<link rel="stylesheet" type="text/css" href="{% static 'css/photoswipe.css' %}" />
			<script src="{% static 'js/klass.min.js' %}"></script>
			<script src="{% static 'js/code.photoswipe.jquery-3.0.5.min.js' %}"></script>

			<script type="text/javascript">
			/*
				Set up PhotoSwipe using jQuery Mobile.
			*/
			$(document).ready(function(){
					$("ul.gallery a").photoSwipe({ enableMouseWheel: false, enableKeyboard: true });
			});
		</script>
	{% endif %}

{% endblock %}

{% block content %}
{% if photos %}
	<div class="gallery-page">
{% endif %}
<h2>{% trans "Trip" %} {{ trip.title }}</h2>
<p>
Created: {{ trip.created }}, last change: {{ trip.modified }}<br/>
Public trip: {% if trip.public %}{% trans "yes" %}{% else %}{% trans "no" %}{% endif %}<br/>
{% if trip.owner == user %}
	<div data-role="controlgroup" data-type="horizontal">
	<a href="{% url 'trips:edit_photos' trip.id %}" class="ui-btn ui-corner-all ui-shadow ui-icon-camera ui-btn-icon-left" data-ajax="false" >{% trans 'Photos' %}</a>
	<a href="{% url 'trips:share' trip.id %}" class="ui-btn ui-corner-all ui-shadow ui-icon-user ui-btn-icon-left" data-ajax="false" >{% trans 'Share trip' %}</a>
	<a href="{% url 'trips:edit' trip.id %}" class="ui-btn ui-corner-all ui-shadow ui-icon-edit ui-btn-icon-left" data-ajax="false" >{% trans 'Edit trip' %}</a>
</div>
{% else %}
	{% trans "Created by " %}<a href="{% url 'users:profile' trip.owner.username %}">{{ trip.owner.username }}</a>
{% endif %}
</p>
<p>{{ trip.trip_begin }} - {{ trip.trip_end }}</p>
<div class="description">
	{{ trip.description|linebreaks }}
</div>

{% if trip.gpx_log %}
	<h3>{% trans 'Trip stats' %}</h3>
	<p id="trip_stats">{% trans 'Loading gpx file..' %}</p>
	<div id="map"></div>

	<script>
		view_gpx('{{ trip.gpx_log.url }}');
	</script>
{% endif %}

{% if photos %}
	<h3>{% trans 'Photos from trip' %}</h3>
	<ul id="Gallery_thumb" class="gallery">
	{% for photo in photos %}
		<li><a href="{{ photo.image.url}}" rel="external" title="{{ photo.title }}" ><img src="{{ photo.thumb.url }}" alt="{{ photo.title}}" /></a></li>
	{% endfor %}
	</ul>
{% endif %}

{% if comment_form or comments%}
	<h3>{% trans 'Comments' %}</h3>

	<div id="comments">
	{% if comment_form %}
		<form id="comment_add" method="post" action="{% url 'trips:add_comment' trip.id %}" data-ajax="false">
		{% csrf_token %}
		{{ comment_form.as_p }}
		<input type="submit" data-icon="comment" value="{% trans 'Add comment' %}" />
		</form>
	{% endif %}

	{% if comments %}
			<ul data-role="listview" data-inset="true">
			{% for comment in comments %}
				<li>
					<h3><a href="{% url 'users:profile' comment.author.username %}">{{ comment.author.username }}</a></h3>
					<p>{{ comment.message }}</p>
					<p class="ui-li-aside"><strong>{{ comment.created }}</strong></p>
				</li>
			{% endfor %}
			</ul>
	{% endif %}
	</div> <!-- comments -->
{% endif %}

{% if photos %}
	</div> <!-- gallery-page -->
{% endif %}

{% endblock %}