wsgi/openshift/trips/urls.py
from django.conf.urls import patterns, url

from trips import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^public/$', views.public, name='public'),
	url(r'^create/$', views.create, name='create'),
	url(r'^view/(?P<tripid>\d+)/$', views.view, name='view'),
	url(r'^comment/(?P<tripid>\d+)/add/$', views.add_comment, name='add_comment'),
	url(r'^delete/(?P<tripid>\d+)/$', views.delete, name='delete'),
	url(r'^edit/(?P<tripid>\d+)/$', views.edit, name='edit'),
	url(r'^photos/(?P<tripid>\d+)/edit/$', views.edit_photos, name='edit_photos'),
	url(r'^photos/(?P<tripid>\d+)/add/$', views.add_photos, name='add_photos'),
	url(r'^share/(?P<tripid>\d+)/$', views.share, name='share'),
	url(r'^share/(?P<tripid>\d+)/remove/(?P<userid>\d+)/$', views.remove_user, name='remove_user'),
	url(r'^share/(?P<tripid>\d+)/add/(?P<userid>\d+)/$', views.add_user, name='add_user'),	
	url(r'^share/(?P<tripid>\d+)/removegroup/(?P<groupid>\d+)/$', views.remove_group, name='remove_group'),
	url(r'^share/(?P<tripid>\d+)/addgroup/(?P<groupid>\d+)/$', views.add_group, name='add_group'),	
)

wsgi/openshift/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
admin.autodiscover()

# include urls patterns and paths from individual apps
urlpatterns = patterns('',
	url(r'^$', 'views.home', name='home'),
	url(r'^dashboard/$', 'views.dashboard', name='dashboard'),
	url(r'^users/', include('users.urls', namespace='users')),
	url(r'^groups/', include('groups.urls', namespace='groups')),
	url(r'^trips/', include('trips.urls', namespace='trips')),
	url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
	#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT, show_indexes=True)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, show_indexes=True)

wsgi/openshift/users/urls.py
from django.conf.urls import patterns, url
from django.core.urlresolvers import reverse

from users import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^profile/(?P<username>\w+)/$', views.profile, name='profile'),
	url(r'^registration/$', views.registration, name='registration'),
	url(r'^login/$', views.user_login, name='login'),
	url(r'^logout/$', views.user_logout, name='logout'),
	url(r'^edit/$', views.edit, name='edit'),
	url(r'^password_change/$', views.password_change, name='password_change'),
	url(r'^search/$', views.search, name='search'),
)

wsgi/openshift/templates/base.html
{% load staticfiles %}
{% load i18n %}

{% trans "The Tourist diary" as the_title %}
{% trans "&copy; 2014 lacike" as the_footer %}

<!DOCTYPE html>
<html lang="en">
<head>
	<title>{% block title %}{{ the_title }}{% endblock %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="{% static 'css/jquery.mobile-1.4.2.min.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/jquery.datetimepicker.min.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}" />

	<script src="{% static 'js/jquery-1.10.2.min.js' %}"></script>
	<script src="{% static 'js/jquery.mobile-1.4.2.min.js' %}"></script>
	<script src="{% static 'js/jquery.datetimepicker.min.js' %}"></script>
	<script src="{% static 'js/custom.js' %}"></script>

	{% block extrahead %}{% endblock %}
	
</head>

<body>
<div data-role="page" data-quicklinks="true" data-url="{{ request.get_full_path }}">
	<div data-role="header">
		<h1>{% block header %}{{ the_title }} <sub>RC</sub>{% endblock %}</h1>
	</div><!-- /header -->

	<div data-role="navbar">
		<ul>
			{% if user.is_authenticated %}
			<li><a href="{% url 'dashboard' %}" data-ajax="false">{% trans 'Dashboard' %}</a></li>
			<li><a href="{% url 'trips:index' %}" data-ajax="false">{% trans 'My trips' %}</a></li>
			<li><a href="{% url 'groups:index' %}" data-ajax="false">{% trans 'My groups' %}</a></li>
			<li><a href="{% url 'users:logout'%}" data-ajax="false">{% trans 'Logout' %} {{ user.username}}</a>

			{% else %}
			<li><a href="{% url 'home'%}" data-ajax="false">{% trans 'Home' %}</a></li>
			<li><a href="{% url 'trips:public' %}" data-ajax="false">{% trans 'Public trips' %}</a></li>
			<li><a href="{% url 'users:login'%}" data-ajax="false">{% trans 'Login' %}</a></li>
			<li><a href="{% url 'users:registration'%}" data-ajax="false">{% trans 'Registration' %}</a>
			{% endif %}
	    </ul>
	</div>

	<div data-role="main" class="ui-content">
		{% if messages %}
		<div id="messages">
			{% for message in messages %}
			<div class="message {{ message.tags }} ui-body ui-body-a">{{ message }}</div>
			{% endfor %}
		</div>
		{% endif %}
		{% if user.is_authenticated %}
		<div class="ui-grid-a two-column">
			<div class="ui-block-a">
		{% endif %}
				<div class="ui-body ui-body-a">
					{% block content %}{% endblock %}
				</div>
			{% if user.is_authenticated %}
			</div>
			<div class="ui-block-b">
				<div class="ui-body ui-body-a">
					<h3>{{ user.username }}</h3>
					<a href="{% url 'users:profile' user.username %}"><img src="{{ user.userprofile.avatar.url }}" alt="{{ user.username }} avatar" /></a>
					<div class="description">
						{{ user.userprofile.about_me|linebreaks }}
					</div>
					<p>
						<a href="{% url 'users:edit' %}" data-ajax="false" >Edit profile</a><br/>
						<a href="{% url 'users:password_change' %}" data-ajax="false" >Change password</a><br/>

						<a href="{% url 'users:logout' %}" data-ajax="false">Logout</a>
</p>
				</div>
	        </div>
		</div>
			{% endif %}
	</div><!-- /content -->

	<div data-role="footer" data-position="fixed">
		<h4>{{ the_footer }}</h4>
	</div><!-- /footer -->


</div><!-- /page -->
</body>
</html>

wsgi/openshift/templates/dashboard.html
{% extends "base.html" %}

{% load i18n %}

{% block content %}
<h2>{% trans "Dashboard" %} </h2>

<h3>{% trans "Personal stats" %}</h3>
<table id="stats">
	<tr><th>{% trans 'Last login' %}:</th><td>{{ stats.last_login }}</td></tr>
	<tr><th>{% trans 'Member since' %}:</th><td>{{ stats.date_joined }}</td></tr>
	<tr><th>{% trans 'Trips shared with me' %}:</th><td>{{ stats.share_trips }}</td></tr>
	<tr><th>{% trans 'All my trips' %}:</th><td>{{ stats.trips }}</td></tr>
	<tr><th>{% trans 'My public trips' %}:</th><td>{{ stats.public_trips }}</td></tr>
	<tr><th>{% trans 'My photos' %}:</th><td>{{ stats.photos }}</td></tr>
	<tr><th>{% trans 'My comments' %}:</th><td>{{ stats.comments }}</td></tr>
	<tr><th>{% trans 'My groups' %}:</th><td>{{ stats.groups }}</td></tr>
	<tr><th>{% trans 'Groups with me' %}:</th><td>{{ stats.share_groups }}</td></tr>
</table>

<h3>{% trans "Trips shared with me" %}</h3>
<span>View all <a href="{% url 'trips:public' %}">public trips.</a></span>

{% if trips %}
<ul data-role="listview" data-filter="true" data-filter-placeholder="{% trans 'Search trips...' %}" data-inset="true">
	{% for trip in trips %}
	<li>
		<a href="{% url 'trips:view' trip.id %}" data-ajax="false" >
			<h3>{{ trip.title }}</h3>
			<p><strong>{{ trip.description|slice:"0:80" }}</strong></p>
			<p>{% trans 'Created: '%}{{ trip.created }}, {% trans 'last change: '%}{{ trip.modified }}</p>
		</a>
		<p class="ui-li-aside"><a href="{% url 'users:profile' trip.owner.username %}">{{ trip.owner.username }}</a></p>
	</li>
	{% endfor %}
</ul>

{% else %}
<p>{% trans "Users have not shared any trip with you yet." %}</p>
{% endif %}

{% endblock %}

wsgi/openshift/templates/home.html
{% extends "base.html" %}

{% load staticfiles %}
{% load i18n %}

{% block content %}

<h2>{% trans "Welcome to the Tourist diary." %}</h2> 
<div id="home-grid" class="ui-grid-b ui-responsive">
	<div class="ui-block-a"><div class="ui-bar ui-bar-a" style="height:280px">
		<p class="notice">{% trans "Notice: current version: Release Candidate (RC)." %}</p>
		<p>{% trans "This page aims to be a place for storing personal notes, photos and gpx logs from your trips and sharing them with friends." %}</p>

		<p>{% trans "You can browse and view all public trips and profiles of our users, but registered users have access to much more functionality. If it sounds interesting for you, you can see some screenshots below and right and continue with " %}<a href="{% url 'users:registration'%}">{% trans "registration"%}</a>.</p>

	</div></div>
	<div class="ui-block-b"><div class="ui-bar ui-bar-a" style="height:280px">
		<figure>
			<img src="{% static 'img/screenshot-trips.png' %}" alt="{% trans 'Trips' %}" />
			<figcaption>{% trans 'Users can create and manage own trips.' %}</figcaption>
		</figure>
	</div></div>
	<div class="ui-block-c"><div class="ui-bar ui-bar-a" style="height:280px">
		<figure>
			<img src="{% static 'img/screenshot-trip.png' %}" alt="{% trans 'Trip' %}" />
			<figcaption>{% trans 'Users can attach photo gallery and gpx log to the trip and comments other trips.' %}</figcaption>
		</figure>
	</div></div>
	<div class="ui-block-a"><div class="ui-bar ui-bar-a" style="height:280px">
		<figure>
			<img src="{% static 'img/screenshot-dashboard.png' %}" alt="{% trans 'Dashboard' %}" />
			<figcaption>{% trans 'Dashboard with personal stats and list of trips shared with user.' %}</figcaption>
		</figure>
	</div></div>
	<div class="ui-block-b"><div class="ui-bar ui-bar-a" style="height:280px">
		<figure>
			<img src="{% static 'img/screenshot-group.png' %}" alt="{% trans 'Groups' %}" />
			<figcaption>{% trans 'Users can create and manage groups for easy sharing' %}</figcaption>
		</figure>
	</div></div>
	<div class="ui-block-c"><div class="ui-bar ui-bar-a" style="height:280px">
		<figure>
			<img src="{% static 'img/screenshot-profile.png' %}" alt="{% trans 'Edit profile' %}" />
			<figcaption>{% trans 'Profile edit page' %}</figcaption>
		</figure>
	</div></div>
</div><!-- /grid-a -->

{% endblock %}