wsgi/openshift/groups/urls.py
from django.conf.urls import patterns, url

from groups import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^create/$', views.create, name='create'),
	url(r'^delete/(?P<groupid>\d+)$', views.delete, name='delete'),
	url(r'^edit/(?P<groupid>\d+)/$', views.edit, name='edit'),
	url(r'^edit/(?P<groupid>\d+)/remove/(?P<userid>\d+)/$', views.remove_user, name='remove_user'),
	url(r'^edit/(?P<groupid>\d+)/add/(?P<userid>\d+)/$', views.add_user, name='add_user'),

)

wsgi/openshift/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
admin.autodiscover()

# include urls patterns and paths from individual apps
urlpatterns = patterns('',
	url(r'^$', 'views.home', name='home'),
	url(r'^dashboard/$', 'views.dashboard', name='dashboard'),
	url(r'^users/', include('users.urls', namespace='users')),
	url(r'^groups/', include('groups.urls', namespace='groups')),
	url(r'^trips/', include('trips.urls', namespace='trips')),
	url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
	#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT, show_indexes=True)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, show_indexes=True)

wsgi/openshift/users/urls.py
from django.conf.urls import patterns, url
from django.core.urlresolvers import reverse

from users import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^profile/(?P<username>\w+)/$', views.profile, name='profile'),
	url(r'^registration/$', views.registration, name='registration'),
	url(r'^login/$', views.user_login, name='login'),
	url(r'^logout/$', views.user_logout, name='logout'),
	url(r'^edit/$', views.edit, name='edit'),
	url(r'^password_change/$', views.password_change, name='password_change'),
	url(r'^search/$', views.search, name='search'),
)

wsgi/openshift/groups/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User

# My custom group for easy sharing trips between users
class CustomGroup(models.Model):
	name = models.CharField(_('name'), max_length=80)
	owner = models.ForeignKey(User)
	users = models.ManyToManyField(User, verbose_name=_('users'),
        blank=True, help_text=_('The users belong to this group.'),
        related_name="custom_groups", related_query_name="group")

	# helper function for validation uniqe group name per user
	def validate_unique_name_owner(self):        
		qs = CustomGroup.objects.filter(name=self.name)
		if qs.filter(owner=self.owner).exists():
			raise ValidationError(_('Name must be unique per user'))

	# Override save() due to validate uniqe group name per user
	def save(self):
		self.validate_unique_name_owner()
		super(CustomGroup, self).save()
		
	# Override the __unicode__() method to return out something meaningful
	def __unicode__(self):
		return self.name + '__' + self.owner.username

wsgi/openshift/groups/forms.py
from django import forms
from django.contrib.auth.models import User
from groups.models import CustomGroup

# Form with user-accessible fields from custom group model
class CustomGroupForm(forms.ModelForm):
	class Meta:
		model = CustomGroup
		fields = ('name',)

wsgi/openshift/groups/views.py
from django.core.urlresolvers import reverse
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from django.shortcuts import get_object_or_404, render, render_to_response
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse
from django.template.context import RequestContext
from django.views.decorators.csrf import csrf_protect
from groups.models import CustomGroup
from groups.forms import CustomGroupForm

# view for display form for create new group and list of user's groups
@csrf_protect
@login_required
def index(request):
	context = RequestContext(request)
	user = request.user
	groups = user.customgroup_set.all()
	group_form = CustomGroupForm()
	return render_to_response('groups/index.html', {'groups': groups, 'form': group_form}, context)

# view for handle creation of new group
@csrf_protect
@login_required
def create(request):
	if request.method == 'POST':
		group_form = CustomGroupForm(data=request.POST)
		if True and group_form.is_valid():
			group = group_form.save(commit=False)
			user = request.user
			group.owner = user
			try:
				group.save()
				messages.success(request, _('Successfully created group ') + group.name)
			except ValidationError, e:
				messages.error(request, e.message)
		else:
			messages.error(request, group_form.errors)
	else:
		group_form = CustomGroupForm()

	return HttpResponseRedirect(reverse('groups:index'))

# view for handle deletion of existing group (also checks validity of such a request, e.g requested user is owner of group)
@login_required
def delete(request, groupid):
	context = RequestContext(request)
	user = request.user
	try:
		group = CustomGroup.objects.get(pk=groupid)
		if group.owner == user:
			group.delete()
			messages.info(request, _('Succesfully deleted group ') + group.name)
		else:
			messages.error(request, _('You have not permission to delete foreign group.'))
	except CustomGroup.DoesNotExist:
		messages.error(request, _('You can not delete non-existing group.'))
	
	return HttpResponseRedirect(reverse('groups:index'))

# view for display editation page of existing group. Also checks validity of such a request
@login_required
def edit(request, groupid):
	context = RequestContext(request)
	user = request.user
	try:
		group = CustomGroup.objects.get(pk=groupid)
		if group.owner != user:
			messages.error(request, _('You have not permission to edit foreign group.'))
			return HttpResponseRedirect(reverse('groups:index'))
	except CustomGroup.DoesNotExist:
		messages.error(request, _('You are not allowed to edit non-existing group.'))
		return HttpResponseRedirect(reverse('groups:index'))
	
	return render_to_response('groups/edit.html', {'group': group, 'users': group.users.all(), 'form': None}, context)

# view for handle removing user from existing group. Also checks validity of such a request
@login_required
def remove_user(request, groupid, userid):
	context = RequestContext(request)
	user = request.user
	try:
		group = CustomGroup.objects.get(pk=groupid)
		if group.owner == user:
			deleted_user = group.users.filter(id=userid).first()
			if deleted_user != None:
				group.users.remove(deleted_user)
				messages.info(request, _('Successfully removed user ') + deleted_user.username)
			else:
				messages.error(request, _('You can not delete non-this-group user.'))
		else:
			messages.error(request, _('You have not permission to edit foreign group.'))
	except CustomGroup.DoesNotExist:
		messages.error(request, _('You can not edit non-existing group.'))
	
	return HttpResponseRedirect(reverse('groups:edit', args=(groupid,)))

# view for handle adding user to existing group. Also checks validity of such a request
@login_required
def add_user(request, groupid, userid):
	context = RequestContext(request)
	user = request.user
	try:
		group = CustomGroup.objects.get(pk=groupid)
		if group.owner == user:
			added_user = group.users.filter(id=userid).first()
			if added_user != None:
				messages.info(request, _('Already in this group: user ') + added_user.username)
			else:
				try:
					added_user = User.objects.get(pk=userid)
					group.users.add(added_user)
					messages.success(request, _('Successfully added user ') + added_user.username)
				except User.DoesNotExist:
					messages.error(request, _('You can not add non-existing user.'))
		else:
			messages.error(request, _('You have not permission to edit foreign group.'))
	except CustomGroup.DoesNotExist:
		messages.error(request, _('You can not edit non-existing group.'))
	
	return HttpResponseRedirect(reverse('groups:edit', args=(groupid,)))

wsgi/openshift/groups/templates/groups/edit.html
{% extends "base.html" %}

{% load staticfiles %}
{% load i18n %}

{% block content %}
<h2>{% trans "Edit group" %} {{ group.name }}</h2>

<script src="{% static 'js/user_add_autocomplete.js' %}"></script>

<ul id="user_add" data-role="listview" data-inset="true" data-filter="true" data-filter-placeholder="{% trans 'Search user for add to this group...' %}" data-split-icon="plus" >
</ul>

{% if users %}
<ul data-role="listview" data-filter="true" data-filter-placeholder="{% trans 'Search users in this group...' %}" data-inset="true" data-split-icon="delete">
	{% for user in users %}
	<li><a href="{% url 'users:profile' user.username %}" ><img src="{{ user.userprofile.avatar.url }}" alt="{{ user.username }}" /><h3>{{ user.username }}</h3><p>{{ user.get_full_name }}</p></a><a href="#remove{{ user.id }}" data-rel="popup" data-position-to="window" data-transition="pop" >{% trans 'Remove' %}</a></li>
	{% endfor %}
</ul>

{% for user in users %}
<div data-role="popup" id="remove{{ user.id }}" class="ui-content" >
	<h3>{% trans 'Remove user' %} {{ user.name }}?</h3>
	<a href="" data-role="button" data-rel="back" data-icon="back" data-inline="true" data-mini="true">{% trans 'Cancel' %}</a>
	<a href="{% url 'groups:remove_user' group.id user.id %}" data-role="button" data-icon="delete" data-inline="true" data-mini="true" data-ajax="false" >Remove</a>
</div>
{% endfor %}

{% else %}
<p>{% trans "You have not added any users to this group yet." %}</p>
{% endif %}

{% endblock %}

wsgi/openshift/groups/templates/groups/index.html
{% extends "base.html" %}

{% load i18n %}

{% block content %}
<h2>{% trans "My groups" %} </h2>

<form id="group_create" method="post" action="{% url 'groups:create' %}" data-ajax="false" >
	{% csrf_token %}
	<fieldset>
		<legend>{% trans 'Create group' %}</legend>
		{{ form.as_p }}
		<input type="submit" value="{% trans 'Create' %}" />
	</fieldset>
</form>

{% if groups %}
<ul data-role="listview" data-filter="true" data-filter-placeholder="{% trans 'Search groups...' %}" data-inset="true" data-split-icon="delete">
	{% for group in groups %}
	<li><a href="{% url 'groups:edit' group.id %}" title="{% trans 'Edit' %}">{{ group.name }}</a><a href="#delete{{ group.id }}" data-rel="popup" data-position-to="window" data-transition="pop" >{% trans 'Delete' %}</a></li>
	{% endfor %}
</ul>

{% for group in groups %}
<div data-role="popup" id="delete{{ group.id }}" class="ui-content" >
	<h3>{% trans 'Delete group' %} {{ group.name }}?</h3>
	<a href="" data-role="button" data-rel="back" data-icon="back" data-inline="true" data-mini="true">{% trans 'Cancel' %}</a>
	<a href="{% url 'groups:delete' group.id %}" data-role="button" data-icon="delete" data-inline="true" data-mini="true" data-ajax="false" >Delete</a>
</div>
{% endfor %}

{% else %}
<p>{% trans "You have not created any groups yet." %}</p>
{% endif %}

{% endblock %}